In [1]:
import numpy as np
print(np.__version__)




2.3.5


In [14]:
import numpy as np

a =np.array([[[1, 2, 3],[4, 5, 6]],[[1, 2, 3],[4, 5, 6]]])

print(a)
print(type(a))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


In [11]:
b = np.array([4, 5, 6])
c =a + b
print(c)

[[ 5  7  9]
 [ 8 10 12]]


In [15]:
print(a.shape) # 배열의 구조 
print(a.size) # 3배열의 총 원소 갯수

(2, 2, 3)
12


In [13]:
sales_q1 = np.array([200,340,150,400])
discounted = sales_q1 * 0.9

print(discounted)

[180. 306. 135. 360.]


In [18]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)


b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)
print(b.shape)



c = np.array([[[1, 2, 3],[4, 5, 6]],[[1, 2, 3],[4, 5, 6]]])
print(c)
print(c.shape)



[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [20]:
import numpy as np

data = [1, 2, 3, 4]
arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# 초기값 사용 
arr = np.zeros((2, 3))  # 2x3 배열
print(arr)


# count = 0 

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
arr = np.ones((3, 2))  # 3x2 배열, 튜플 형태
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
arr = np.arange(0, 10, 2)  # 0부터 9까지 2씩 증가하는 값
print(arr)

[0 2 4 6 8]


In [24]:
arr =np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [184]:
arr = np.random.randn(2, 3)  # 2x3 배열
print(arr)


[[-1.1146816   0.11496287  0.48992076]
 [ 1.15969854 -0.10181931 -0.53706705]]


In [189]:
arr = np.array([[1,2,3],[4,5,6]])

#배열의 구조(모양) 
print((arr.shape))

#배열의 차원
print(arr.ndim)

#데이터 타입 
print(arr.dtype)


arr = np.array(["한","글"])


(2, 3)
2
int64


In [190]:
#1 차원 배열의 인덱싱 

import numpy as np 

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[2])

10
30


In [ ]:
#2차원 배열 인덱싱 

arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8 ,9]])
print(arr[0,1])
print(arr[2,2])

2
9


In [192]:
print(arr[0][1])
print(arr[0,1])

2
2


In [ ]:
arr = np.array([[[1, 2, 3],[4, 5 ,6]],[[7, 8, 9],[10, 11, 12 ]]]) # 백터화 상태에 따라 1번 - 차원,행,열 2번- 행,열,채널
print(arr[1, 0, 0]) #7
print(arr[0, 1, 1]) #5 
print(arr[1, 1, 2]) #12

7
5
12


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # 0번째 요소 출력 (10)
print(arr[2])  # 2번째 요소 출력 (30)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 1])  # 0번째 행, 1번째 열의 요소 출력 (2)
print(arr[2, 2])  # 2번째 행, 2번째 열의 요소 출력 (9)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 0, 2])  # 1번째 차원, 0번째 행, 2번째 열의 요소 출력 (9)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # 1번째 인덱스부터 3번째 인덱스까지의 값 출력 ([20, 30, 40])
print(arr[:3])   # 처음부터 2번째 인덱스까지 출력 ([10, 20, 30])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1:, :2])  # 1번째 행부터 끝까지, 0번째와 1번째 열만 출력 ([[4, 5], [7, 8]])

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[:, 1, :2])  # 각 차원에서 1번째 행의 처음 두 열 출력 ([[4, 5], [10, 11]])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # 0번째, 2번째, 4번째 인덱스를 선택
print(arr[idx])   # [10, 30, 50]    

In [199]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1, 2]
cols = [2, 1, 0]
print(arr[rows, cols])  # [3, 5, 7]

[3 5 7]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 30])  # [40, 50]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[(arr > 4) & (arr < 9 )])  # [5, 6, 7, 8, 9]

[5 6 7 8 9]


In [202]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # [5, 7, 9]

[5 7 9]


In [203]:
print(arr1 - arr2)

[-3 -3 -3]


In [204]:
print(arr1*arr2)

[ 4 10 18]


In [205]:
print(arr1 / arr2)

[0.25 0.4  0.5 ]


In [209]:
print(arr1 ** arr2)

[  1  32 729]


In [210]:
print([1, 2, 3]*2)
print(np.array([1, 2, 3]) * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [211]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2))  # 1*4 + 2*5 + 3*6 = 32

32


In [212]:
arr2d = np.array([[1, 2], [3, 4]])
arr1d = np.array([5, 6])
print(np.dot(arr2d, arr1d))
# [1*5 + 2*6, 3*5 + 4*6]
# [17, 39]

[17 39]


In [ ]:
arr2d_1 = np.array([[1, 2], [3, 4]])
arr2d_2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr2d_1, arr2d_2))
# [[1*5 + 2*7, 1*6 + 2*8],
#  [3*5 + 4*7, 3*6 + 4*8]]
# [[19, 22],
#  [43, 50]]

print(arr2d_1 @ arr2d_2)

[[19 22]
 [43 50]]


In [216]:
arr = np.array([1, 2, 3])
print(arr + 10)


[11 12 13]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([1, 2, 3])
print(arr2d + arr1d)
# [[2, 4, 6],
#  [5, 7, 9]]

In [ ]:
arr3d = np.random.rand(3, 1, 4)  # 3x1x4 배열
arr2d = np.random.rand(4, 4)     # 4x4 배열

# 브로드캐스팅을 통해 3차원 배열과 2차원 배열 간 연산 수행

result = arr3d + arr2d
print(result.shape)  # 결과: 3x4x4 배열a


(3, 4, 4)


In [225]:
arr2d =  np.array([[1, 2, 3],[4, 5, 6]])
rows = np.array([10, 20 ,30])
col = np.array ([[10],[20]])


print(arr2d.shape)
print(rows.shape)
print(col.shape)



print(arr2d+rows)
print(arr2d+col)

(2, 3)
(3,)
(2, 1)
[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [24 25 26]]


In [226]:
arr = np.array([10, 20, 30])
print(arr > 15)  # [False, True, True]


[False  True  True]


In [227]:
print(arr == 20)  # [False, True, False]
print(arr != 20)  # [True, False, True]

[False  True False]
[ True False  True]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])
print(arr1 > arr2)  # [False, False, True]

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())  # 15

In [ ]:
print(arr.max())  # 5
print(arr.min())  # 1

In [ ]:
print(arr.mean())  # 3.0

In [ ]:
print(arr.std())  # 표준편차
print(arr.var())  # 분산

In [228]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.sum(axis=0))  # [5, 7, 9] (각 열의 합)
print(arr2d.sum(axis=1))  # [6, 15] (각 행의 합)

[5 7 9]
[ 6 15]


In [229]:
import numpy as np
arr = np.array([30, 10, 20, 40, 50])
sorted_arr = np.sort(arr)
print(sorted_arr)  # [10, 20, 30, 40, 50]

[10 20 30 40 50]


In [230]:
sorted_arr_desc = np.sort(arr)[::-1]
print(sorted_arr_desc)  # [50, 40, 30, 20, 10]

[50 40 30 20 10]


In [231]:
arr2d = np.array([[5, 2, 3], [8, 4, 1]])
sorted_arr2d = np.sort(arr2d)  # 행 단위로 정렬
print(sorted_arr2d)
# [[2, 3, 5],
#  [1, 4, 8]]

[[2 3 5]
 [1 4 8]]


In [232]:
sorted_arr_axis0 = np.sort(arr2d, axis=0)
print(sorted_arr_axis0)
# [[5, 2, 1],
#  [8, 4, 3]]

[[5 2 1]
 [8 4 3]]


In [233]:
sorted_arr_axis1 = np.sort(arr2d, axis=1)
print(sorted_arr_axis1)
# [[2, 3, 5],
#  [1, 4, 8]]

[[2 3 5]
 [1 4 8]]


In [234]:
arr = np.array([30, 10, 20])
sorted_indices = np.argsort(arr)
print(sorted_indices)  # [1, 2, 0] (정렬된 순서의 인덱스)

# 인덱스를 사용하여 배열을 정렬
print(arr[sorted_indices])  # [10, 20, 30]

[1 2 0]
[10 20 30]


In [235]:
arr2d = np.array([[3, 1, 2], [6, 4, 5]])
sorted_indices = np.argsort(arr2d, axis=1)  # 각 행을 기준으로 인덱스를 반환
print(sorted_indices)
# [[1, 2, 0],
#  [1, 2, 0]]

[[1 2 0]
 [1 2 0]]


In [236]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)  # [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [237]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
merged_arr = np.concatenate((arr1, arr2), axis=0)
print(merged_arr)
# [[1, 2],
#  [3, 4],
#  [5, 6],
#  [7, 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [243]:

merged_arr = np.concatenate((arr1, arr2), axis=1)
print(merged_arr)
# [[1, 2, 5, 6],
#  [3, 4, 7, 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.vstack((arr1, arr2))
print(merged_arr)
# [[1, 2, 3],
#  [4, 5, 6]]

In [244]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.hstack((arr1, arr2))
print(merged_arr)  # [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [245]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)
# [[1, 2, 3],
#  [4, 5, 6]]

[[1 2 3]
 [4 5 6]]


In [246]:
stacked_arr = np.stack((arr1, arr2), axis=1)
print(stacked_arr)
# [[1, 4],
#  [2, 5],
#  [3, 6]]

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr1  = np.stack((arr1,arr2),axis = 0 )
print(arr1)



In [3]:
import time
size = 1000000
python_list = list(range(size))

start_time = time.time()
python_list = [x * 2 for x in python_list]
print("Python 리스트 성능:", time.time() - start_time)

Python 리스트 성능: 0.045220136642456055


In [282]:
import numpy as np
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2
print("NumPy 배열 성능:", time.time() - start_time)

NumPy 배열 성능: 0.003055095672607422


In [4]:
size = 1000000
python_list = list(range(size))
result = []

start_time = time.time()
for x in python_list:
    result.append(x * 2)
print("반복문 성능:", time.time() - start_time)

반복문 성능: 0.04623985290527344


In [5]:
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2  # 벡터화 연산
print("벡터화 성능:", time.time() - start_time)

벡터화 성능: 0.0014619827270507812


In [6]:
arr = np.array([1, 2, 3], dtype='int64')
print(arr.nbytes)  # 배열이 사용하는 메모리 크기 (bytes)

24


In [7]:
arr = np.array([1, 2, 3], dtype='int32')
print(arr.nbytes)  # 더 작은 메모리 사용

12


In [13]:
size = 100000000  # 1억 개의 요소
arr = np.random.rand(size)  # 난수 배열 생성

start_time = time.time()
result = np.sum(arr)  # 배열의 합 계산
print("대용량 데이터 합계 성능:", time.time() - start_time)

대용량 데이터 합계 성능: 0.08147096633911133


In [14]:
# 1GB 크기의 파일을 생성 후 메모리 맵핑 방식으로 읽기
size = 10**9
arr = np.memmap('large_file.dat', dtype='float32', mode='w+', shape=(size,))
arr[:100] = np.random.rand(100)  # 일부 데이터를 파일에 쓰기

# 파일을 메모리 맵핑하여 읽기
memmap_arr = np.memmap('large_file.dat', dtype='float32', mode='r', shape=(size,))
print(memmap_arr[:10])  # 메모리에 로드된 일부 데이터만 접근

[0.68143106 0.17654595 0.46193874 0.53098875 0.372773   0.4879499
 0.33400267 0.32152736 0.03535691 0.9612987 ]
